name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand({ping: 1})'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Lint code
        run: npm run lint

      - name: Run tests
        env:
          DATABASE_URL: mongodb+srv://chris:chris@cluster0.k1npp.mongodb.net/credit-jambo
          JWT_SECRET: credit-jambo-secret
          JWT_REFRESH_SECRET: credit-jambo-refresh
          JWT_REFRESH_EXPIRES_IN: 5h
          JWT_EXPIRES_IN: 2h
          NODE_ENV: development
        run: npm test

      - name: Build the project
        run: npm run build

      - name: Generate documentation
        if: success()
        run: npm run doc

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Deploy to Production
        env:
          DATABASE_URL: mongodb+srv://chris:chris@cluster0.k1npp.mongodb.net/credit-jambo
          JWT_SECRET: credit-jambo-secret
          JWT_REFRESH_SECRET: credit-jambo-refresh
          JWT_REFRESH_EXPIRES_IN: 5h
          JWT_EXPIRES_IN: 2h
          NODE_ENV: development
        run: |
          npm run build
          npm start
